from __future__ import annotations

from pathlib import Path
import matplotlib.pyplot as plt
import pandas as pd


def _prepare_path(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def save_bar_chart(df: pd.DataFrame, x: str, y: str, title: str, path: Path, rotate_labels: bool = True) -> str:
    _prepare_path(path)
    ax = df.plot(kind="bar", x=x, y=y, legend=False, figsize=(9, 5))
    ax.set_title(title)
    ax.set_xlabel(x.replace("_", " ").title())
    ax.set_ylabel(y.replace("_", " ").title())
    if rotate_labels:
        plt.xticks(rotation=35, ha="right")
    plt.tight_layout()
    plt.savefig(path, dpi=160)
    plt.close()
    return str(path)


def save_line_chart(df: pd.DataFrame, x: str, y: str, title: str, path: Path) -> str:
    _prepare_path(path)
    ax = df.plot(kind="line", x=x, y=y, marker="o", legend=False, figsize=(9, 5))
    ax.set_title(title)
    ax.set_xlabel(x.replace("_", " ").title())
    ax.set_ylabel(y.replace("_", " ").title())
    plt.xticks(rotation=35, ha="right")
    plt.tight_layout()
    plt.savefig(path, dpi=160)
    plt.close()
    return str(path)


def save_pipeline_architecture(path: Path) -> str:
    """Create a simple architecture diagram for README and interview walkthroughs."""
    _prepare_path(path)
    fig, ax = plt.subplots(figsize=(12, 3.2))
    ax.axis("off")
    steps = ["Raw CSV", "Extract", "Transform", "Quality Checks", "PostgreSQL", "Reports"]
    x_positions = range(len(steps))
    for x, label in zip(x_positions, steps):
        ax.text(x, 0.5, label, ha="center", va="center", fontsize=11,
                bbox=dict(boxstyle="round,pad=0.45", facecolor="white", edgecolor="black"))
        if x < len(steps) - 1:
            ax.annotate("", xy=(x + 0.72, 0.5), xytext=(x + 0.28, 0.5), arrowprops=dict(arrowstyle="->", lw=1.5))
    ax.set_xlim(-0.7, len(steps) - 0.3)
    ax.set_ylim(0, 1)
    fig.suptitle("City Service Requests ETL Pipeline", fontsize=14, y=0.95)
    plt.tight_layout()
    plt.savefig(path, dpi=180, bbox_inches="tight")
    plt.close()
    return str(path)


def save_postgres_schema_diagram(path: Path) -> str:
    _prepare_path(path)
    fig, ax = plt.subplots(figsize=(9, 5))
    ax.axis("off")
    tables = {
        "service_requests": ["request_id", "borough", "complaint_type", "status", "resolution_hours"],
        "summary_by_borough": ["borough", "request_count", "closed_rate", "avg_resolution_hours"],
        "summary_by_complaint": ["complaint_type", "request_count", "avg_resolution_hours"],
        "daily_volume": ["created_day", "request_count"],
    }
    positions = [(0.16, 0.58), (0.56, 0.72), (0.56, 0.46), (0.56, 0.20)]
    for (name, columns), (x, y) in zip(tables.items(), positions):
        text = name + "\n" + "\n".join(f"• {col}" for col in columns)
        ax.text(x, y, text, ha="left", va="center", fontsize=10,
                bbox=dict(boxstyle="round,pad=0.55", facecolor="white", edgecolor="black"))
    for y in [0.72, 0.46, 0.20]:
        ax.annotate("", xy=(0.54, y), xytext=(0.38, 0.58), arrowprops=dict(arrowstyle="->", lw=1.2))
    fig.suptitle("PostgreSQL Reporting Tables", fontsize=14)
    plt.savefig(path, dpi=180, bbox_inches="tight")
    plt.close()
    return str(path)


def write_pipeline_summary(clean_df: pd.DataFrame, quality_report: pd.DataFrame, output_path: Path, database_label: str = "PostgreSQL") -> str:
    _prepare_path(output_path)
    closed_rate = clean_df["is_closed"].mean() * 100 if len(clean_df) else 0
    avg_resolution = clean_df["resolution_hours"].mean()
    top_complaint = clean_df["complaint_type"].value_counts().idxmax() if len(clean_df) else "N/A"
    failed_checks = quality_report[quality_report["status"].eq("fail")]
    content = f"""City Service Requests ETL Summary
=================================

Rows processed: {len(clean_df)}
Database target: {database_label}
Closed rate: {closed_rate:.1f}%
Average resolution hours: {avg_resolution:.2f}
Top complaint type: {top_complaint}
Failed data quality checks: {len(failed_checks)}

This file is generated by scripts/run_pipeline.py and provides a quick summary of the latest ETL run.
"""
    output_path.write_text(content)
    return str(output_path)
